apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: valley-tech-stripprefix
  namespace: websites
  labels:
    app.kubernetes.io/name: valley-tech-support
    app.kubernetes.io/part-of: smadp
spec:
  stripPrefix:
    prefixes:
      - /vts