set service dhcp-server shared-network-name LABNET subnet 192.168.20.0/24 static-mapping um690 ip-address 192.168.20.100
set service dhcp-server shared-network-name LABNET subnet 192.168.20.0/24 static-mapping um690 mac '58:47:ca:70:aa:02'
set service dhcp-server shared-network-name LABNET subnet 192.168.20.0/24 static-mapping node1 ip-address 192.168.20.101
set service dhcp-server shared-network-name LABNET subnet 192.168.20.0/24 static-mapping node1 mac 'd8:cb:8a:01:7a:89'
set service dhcp-server shared-network-name LABNET subnet 192.168.20.0/24 static-mapping node2 ip-address 192.168.20.102
set service dhcp-server shared-network-name LABNET subnet 192.168.20.0/24 static-mapping node2 mac '44:8a:5b:dd:a0:c5'