set service ssh port 22
set service ssh listen-address 192.168.10.1
set service ssh listen-address 192.168.20.1
set system login user vyos authentication public-keys grokos key AAAAC3NzaC1lZDI1NTE5AAAAIIuNIxDK5nTIAUxHJ20/VLIGIpWl8AsQxcHW0YFOMc5x
set system login user vyos authentication public-keys grokos type ssh-ed25519