#!/usr/bin/env bash
# Install / refresh Netdata PARENT on this host (intended: um690).
# Generates stream API key, writes runtime configs, starts Docker Compose.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME="${DIR}/runtime"
cd "${DIR}"

log() { echo "=== $* ==="; }
die() { echo "ERROR: $*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker not found — install Docker CE first"
if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose)
else
  die "docker compose plugin not available"
fi

mkdir -p "${RUNTIME}"
chmod 700 "${RUNTIME}"

# --- API key (stable across re-runs if already present) ---
KEY_FILE="${RUNTIME}/stream-api-key"
if [[ -f "${KEY_FILE}" ]]; then
  API_KEY="$(tr -d '[:space:]' < "${KEY_FILE}")"
  log "Reusing existing stream API key"
else
  if command -v uuidgen >/dev/null 2>&1; then
    API_KEY="$(uuidgen)"
  else
    API_KEY="$(cat /proc/sys/kernel/random/uuid)"
  fi
  printf '%s\n' "${API_KEY}" > "${KEY_FILE}"
  chmod 600 "${KEY_FILE}"
  log "Generated new stream API key → ${KEY_FILE}"
fi

# --- Parent stream.conf (accept children) ---
cat > "${RUNTIME}/stream.conf" <<EOF
# Auto-generated by install-parent.sh — parent receives child streams
[${API_KEY}]
    enabled = yes
    allow from = *
    default history = 3600
    default memory mode = dbengine
    health enabled by default = auto
    allow multiple connections = yes
EOF
chmod 644 "${RUNTIME}/stream.conf"

# --- Health notify: Telegram if env present, else stub ---
NOTIFY="${RUNTIME}/health_alarm_notify.conf"
if [[ -f "${HOME}/.config/valley-tech/telegram.env" ]]; then
  # shellcheck disable=SC1091
  source "${HOME}/.config/valley-tech/telegram.env"
fi

if [[ -n "${TELEGRAM_BOT_TOKEN:-}" && -n "${TELEGRAM_CHAT_ID:-}" ]]; then
  log "Writing Telegram notify config from ~/.config/valley-tech/telegram.env"
  cat > "${NOTIFY}" <<EOF
# Auto-generated — Telegram alerts for Valley Tech Support
SEND_TELEGRAM="YES"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}"
DEFAULT_RECIPIENT_TELEGRAM="${TELEGRAM_CHAT_ID}"
EOF
else
  log "No Telegram env yet — writing DISABLED stub (YOU will configure later)"
  cat > "${NOTIFY}" <<EOF
# Telegram not configured yet.
# YOU: create ~/.config/valley-tech/telegram.env then re-run this script.
# See parent/telegram.md
SEND_TELEGRAM="NO"
EOF
fi
chmod 600 "${NOTIFY}" 2>/dev/null || chmod 644 "${NOTIFY}"

# Export key for child installs (local only)
ENV_OUT="${HOME}/.config/valley-tech/netdata-stream.env"
mkdir -p "${HOME}/.config/valley-tech"
chmod 700 "${HOME}/.config/valley-tech"
{
  echo "# Generated $(date -Iseconds) — use on children"
  echo "NETDATA_STREAM_API_KEY=${API_KEY}"
  # Prefer Tailscale IP of this host if available
  TS_IP="$(tailscale ip -4 2>/dev/null | head -1 || true)"
  if [[ -n "${TS_IP}" ]]; then
    echo "NETDATA_PARENT_DESTINATION=${TS_IP}:19999"
  else
    echo "NETDATA_PARENT_DESTINATION=REPLACE_WITH_PARENT_TAILSCALE_IP:19999"
  fi
} > "${ENV_OUT}"
chmod 600 "${ENV_OUT}"
log "Child connection file → ${ENV_OUT}"

log "Pulling image & starting parent"
"${COMPOSE[@]}" pull
"${COMPOSE[@]}" up -d

sleep 3
if curl -fsS -o /dev/null --max-time 5 "http://127.0.0.1:19999/api/v1/info"; then
  log "Parent UI responding on http://127.0.0.1:19999"
else
  echo "WARN: Parent not answering yet — check: docker logs netdata-parent"
fi

echo ""
echo "----------------------------------------"
echo "PARENT READY"
echo "  UI (local):     http://127.0.0.1:19999"
echo "  UI (Tailscale): http://$(hostname -s).$(tailscale status --json 2>/dev/null | grep -o '"MagicDNSSuffix": "[^"]*"' | head -1 | cut -d'"' -f4 2>/dev/null || echo 'taile52ad9.ts.net'):19999"
echo "  Stream key:     ${KEY_FILE}"
echo "  Child env:      ${ENV_OUT}"
echo ""
echo "YOU (if Telegram not set yet):"
echo "  1. Create bot via BotFather; get chat_id"
echo "  2. Write ~/.config/valley-tech/telegram.env  (see parent/telegram.md)"
echo "  3. Re-run: bash $0"
echo "  4. In Netdata: raise a test alarm OR use child offline test later"
echo "----------------------------------------"
