#!/bin/bash
#
# phase-05-automation.sh
# Phase 5: Deploy inotify watcher, cron, Tailscale serve, final scan.
# Reads previous docs.
# Outputs: phase-docs/05-complete.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_DIR="$SCRIPT_DIR/phase-docs"
SCAN_FILE="$DOCS_DIR/01-host-scan.json"
USER_FILE="$DOCS_DIR/04-user-symlinks.json"

CURRENT_USER=$(python3 -c "import json,sys; print(json.load(open('$SCAN_FILE'))['current_user'])")
CURRENT_HOME=$(python3 -c "import json,sys; print(json.load(open('$SCAN_FILE'))['current_home'])")
WEB_ROOT=$(python3 -c "import json,sys; d=json.load(open('$SCAN_FILE')); print(d.get('recommendations',{}).get('web_root','/var/www/nextcloud'))")

FOLDERS=(Documents Pictures Music Videos Public Templates Downloads Desktop Backups Notes Projects)

WATCHER_SCRIPT="$SCRIPT_DIR/watch-and-scan.sh"
CRON_LINE="*/2 * * * * sudo -u www-data php $WEB_ROOT/occ files:scan $CURRENT_USER --quiet 2>/dev/null || true"

OUTPUT_FILE="$DOCS_DIR/05-complete.json"

echo "=== Phase 5: Automation & Access ==="

# Deploy watcher script
cat > "$WATCHER_SCRIPT" << 'WATCHER'
#!/bin/bash
# watch-and-scan.sh - generated by phase-05
set -euo pipefail
WEB_ROOT="/var/www/nextcloud"
NC_USER="CURRENT_USER_PLACEHOLDER"
HOME_DIR="CURRENT_HOME_PLACEHOLDER"
FOLDERS=(Documents Pictures Music Videos Public Templates Downloads Desktop Backups Notes Projects)

log() { echo "[$(date '+%F %T')] $*"; }

if ! command -v inotifywait >/dev/null; then
    echo "Install inotify-tools"
    exit 1
fi

WATCH_PATHS=()
for d in "${FOLDERS[@]}"; do
    p="$HOME_DIR/$d"
    [ -d "$p" ] && WATCH_PATHS+=("$p")
done

inotifywait -m -r -e create,modify,delete,move,close_write --format '%w%f %e' "${WATCH_PATHS[@]}" | while read path event; do
    for d in "${FOLDERS[@]}"; do
        if [[ "$path" == "$HOME_DIR/$d"* ]]; then
            log "Change in $d"
            sudo -u www-data php "$WEB_ROOT/occ" files:scan "$NC_USER" --path="/$d" --quiet 2>/dev/null || true
            break
        fi
    done
done
WATCHER

sed -i "s|CURRENT_USER_PLACEHOLDER|$CURRENT_USER|g" "$WATCHER_SCRIPT"
sed -i "s|CURRENT_HOME_PLACEHOLDER|$CURRENT_HOME|g" "$WATCHER_SCRIPT"
chmod +x "$WATCHER_SCRIPT"

# Install inotify if needed
sudo apt install -y inotify-tools 2>/dev/null || true

# Cron
(crontab -l 2>/dev/null | grep -v "files:scan $CURRENT_USER" ; echo "$CRON_LINE") | crontab -

# Tailscale serve (assumes tailscale is logged in)
if command -v tailscale >/dev/null; then
    echo "Configuring Tailscale serve..."
    sudo tailscale set --operator="$CURRENT_USER" 2>/dev/null || true
    tailscale serve --bg http://127.0.0.1:8080 2>/dev/null || true
fi

# Final scan
sudo -u www-data php "$WEB_ROOT/occ" files:scan "$CURRENT_USER" || true

cat > "$OUTPUT_FILE" << EOF
{
  "phase": 5,
  "timestamp": "$(date -Iseconds)",
  "watcher_script": "$WATCHER_SCRIPT",
  "cron_installed": true,
  "tailscale_serve": "configured (run manually if needed)",
  "final_scan_done": true,
  "access_url": "https://<your-tailscale-hostname> (via tailscale)",
  "notes": "Run the watcher with: nohup $WATCHER_SCRIPT > /tmp/watch.log 2>&1 &"
}
EOF

echo ""
echo "=== Phase 5 Complete - Setup Finished ==="
echo "Document: $OUTPUT_FILE"
echo ""
echo "To start near-real-time sync:"
echo "  nohup $WATCHER_SCRIPT > /tmp/nextcloud-watch.log 2>&1 &"
echo ""
echo "Your local Google Drive replacement is ready."
echo "================================================================"