#!/usr/bin/env bash
# Install Netdata CHILD on Ubuntu (M93p tiny, appliance Linux, etc.) and stream to parent.
#
# Usage (on the child host):
#   sudo bash install-child.sh
#   sudo bash install-child.sh /path/to/netdata-stream.env
#
# Env file must define:
#   NETDATA_STREAM_API_KEY=...
#   NETDATA_PARENT_DESTINATION=100.x.x.x:19999
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${1:-${DIR}/netdata-stream.env}"

die() { echo "ERROR: $*" >&2; exit 1; }
log() { echo "=== $* ==="; }

[[ "$(id -u)" -eq 0 ]] || die "Run with sudo: sudo bash $0 [env-file]"

if [[ ! -f "${ENV_FILE}" ]]; then
  die "Missing env file: ${ENV_FILE}
Copy netdata-stream.env from the parent (created by parent/install-parent.sh)
or from USB secrets/ folder after YOU populate it."
fi

# shellcheck disable=SC1090
source "${ENV_FILE}"
[[ -n "${NETDATA_STREAM_API_KEY:-}" ]] || die "NETDATA_STREAM_API_KEY not set in ${ENV_FILE}"
[[ -n "${NETDATA_PARENT_DESTINATION:-}" ]] || die "NETDATA_PARENT_DESTINATION not set in ${ENV_FILE}"
[[ "${NETDATA_PARENT_DESTINATION}" != REPLACE* ]] || die "Set real parent Tailscale IP in env file"

log "Installing Netdata agent (needs internet on this host)"
KICKSTART_CACHE="${DIR}/../vendor/kickstart.sh"
if [[ -f "${KICKSTART_CACHE}" ]]; then
  bash "${KICKSTART_CACHE}" --dont-wait --stable-channel --disable-telemetry
else
  curl -fsSL https://get.netdata.cloud/kickstart.sh -o /tmp/netdata-kickstart.sh
  bash /tmp/netdata-kickstart.sh --dont-wait --stable-channel --disable-telemetry
fi

# Locate stream.conf
STREAM_CONF=""
for candidate in /etc/netdata/stream.conf /opt/netdata/etc/netdata/stream.conf; do
  if [[ -f "${candidate}" ]] || [[ -d "$(dirname "${candidate}")" ]]; then
    STREAM_CONF="${candidate}"
    break
  fi
done
[[ -n "${STREAM_CONF}" ]] || die "Could not find Netdata config dir after install"

# Prefer edit-config if present
EDIT_CONFIG="$(dirname "${STREAM_CONF}")/edit-config"
if [[ -x "${EDIT_CONFIG}" ]]; then
  # Ensure stream.conf exists via edit-config stock copy
  (cd "$(dirname "${STREAM_CONF}")" && ./edit-config stream.conf >/dev/null 2>&1) || true
fi

# If still missing, create
if [[ ! -f "${STREAM_CONF}" ]]; then
  mkdir -p "$(dirname "${STREAM_CONF}")"
  touch "${STREAM_CONF}"
fi

log "Writing child stream.conf → ${STREAM_CONF}"
# Backup
cp -a "${STREAM_CONF}" "${STREAM_CONF}.bak.$(date +%s)" 2>/dev/null || true

# Write minimal child stream section at top (Netdata merges; replace whole file for field simplicity)
cat > "${STREAM_CONF}" <<EOF
# Valley Tech child — generated by install-child.sh
[stream]
    enabled = yes
    destination = ${NETDATA_PARENT_DESTINATION}
    api key = ${NETDATA_STREAM_API_KEY}
    timeout seconds = 60
    default port = 19999
    send charts matching = *
    buffer size bytes = 1048576
    reconnect delay seconds = 5
    initial clock resync iterations = 60
EOF

log "Restarting Netdata"
systemctl restart netdata 2>/dev/null || service netdata restart 2>/dev/null || \
  /usr/sbin/netdata -D &  # fallback

sleep 2
systemctl is-active netdata 2>/dev/null && log "netdata service active" || echo "WARN: check netdata status manually"

echo ""
echo "----------------------------------------"
echo "CHILD INSTALLED"
echo "  Streaming to: ${NETDATA_PARENT_DESTINATION}"
echo "  On parent UI: confirm this hostname appears under streaming nodes"
echo "  Next: bash ../phases/06-verify-monitoring.sh (or package INSTALL.md §C)"
echo "----------------------------------------"
